# Application
spring.application.name=workly-backend

server.port=8080

# MongoDB
spring.data.mongodb.uri=mongodb+srv://himansithdilnuka_db_user:H2DQ4Fw8NpyYi0iJ@cluster0.jdwqvwq.mongodb.net/worklydb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=worklydb

# JWT
jwt.secret=WorklyJWTSecretKey2026SuperSecureAuthenticationSystemForIndustryLevelProject256Bit

jwt.expiration=86400000

# Jackson
spring.jackson.time-zone=Asia/Colombo

# Logging
logging.level.org.springframework.security=DEBUG

# Error Handling
server.error.include-message=always
server.error.include-binding-errors=always