spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://himansithdilnuka_db_user:H2DQ4Fw8NpyYi0iJ@cluster0.jdwqvwq.mongodb.net/worklydb?retryWrites=true&w=majority&appName=Cluster0

spring.data.mongodb.database=worklydb

server.port=8080