spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://sathirasugeesvara_db_user:Sathira123DBmDB@workly-cluster.e7fcvtl.mongodb.net/?appName=workly-cluster

spring.data.mongodb.database=worklydb